src/Fakebook/models/post.py
from .comment import Comment
from datetime import datetime
import MySQLdb.cursors


class Post:
    def __init__(
        self,
        db=None,
        post_id=0,
        user_id=0,
        creator_name="",
        description="",
        likes=0,
        creation_date: datetime = None,
    ):
        self.db = db
        
        if db:
            self.cursor = db.connection.cursor(MySQLdb.cursors.DictCursor)

        self.post_id = post_id
        self.user_id = user_id
        self.creator_name = creator_name
        self.description = description
        self.likes = likes
        self.creation_date = creation_date

        self.__get_post()
        self.comments = dict()
        
    def __get_post(self):
        cursor = self.cursor
        cursor.execute(
            "SELECT users_tb.username, posts_tb.user_id, posts_tb.description, posts_tb.likes, posts_tb.creation_date FROM posts_tb INNER JOIN users_tb ON posts_tb.user_id = users_tb.id WHERE posts_tb.post_id = %s",
            (
                self.post_id,
            ),
        )
        post = cursor.fetchone()
        
        if post:
            self.user_id = post['user_id']
            self.creator_name = post['username']
            self.description = post['description']
            self.likes = post['likes']
            self.creation_date = post['creation_date'].strftime("%b %d, %Y %I:%M %p")

    def get_comments(self):
        cursor = self.cursor
        cursor.execute(
            "SELECT users_tb.username, comments_tb.comment_id, comments_tb.commenter_id, comments_tb.comment, comments_tb.creation_date, comments_tb.comment_replied_to FROM comments_tb INNER JOIN posts_tb ON comments_tb.post_id = posts_tb.post_id INNER JOIN users_tb ON users_tb.id = comments_tb.commenter_id WHERE posts_tb.post_id = %s ORDER BY comments_tb.creation_date DESC",
            (self.post_id,),
        )
        comments = cursor.fetchall()

        if comments:
            for comment in comments:
                item = Comment(
                    comment_id=comment["comment_id"],
                    commenter_id=comment["commenter_id"],
                    commenter_name=comment["username"],
                    text=comment["comment"],
                    creation_date=comment["creation_date"].strftime("%b %d, %Y %I:%M %p"),
                    comment_replied_to=comment["comment_replied_to"]
                )
                self.comments[comment["comment_id"]] = item
        else:
            return None

src/Fakebook/auth.py
from datetime import datetime
from flask import current_app as app
from flask import Blueprint, render_template, redirect, request, url_for, session
from flask_mysqldb import MySQL
import MySQLdb.cursors
import MySQLdb.cursors, re, hashlib

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    # Displays error message on website
    msg = ""

    # When user clicks on the login button,
    # check to make sure it's a POST request.
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        # Retrieve hashed password
        hashed_password = password + app.secret_key
        hashed_password = hashlib.sha1(hashed_password.encode())
        password = hashed_password.hexdigest()

        # Check if user exists in database
        db = app.config['DATABASE']
        cursor: MySQLdb.cursors.Cursor = db.connection.cursor(
            MySQLdb.cursors.DictCursor
        )
        cursor.execute(
            "SELECT * FROM users_tb WHERE username = %s AND password = %s",
            (
                username,
                password,
            ),
        )
        user = cursor.fetchone()

        # Create session data for user if user exists
        if user:
            session["loggedin"] = True
            session["id"] = user["id"]
            session["username"] = username
            
            fullname = f"{user['first_name']} {user['last_name']}"
            session["fullname"] = fullname

            return redirect(url_for("views.home"))
        else:
            msg = "Invalid username or password. Please try again."

    return render_template("login.html", msg=msg)


@auth.route("/logout")
def logout():
    # Remove session data counts as logging a user out
    session.pop("loggedin", None)
    session.pop("id", None)

    return redirect(url_for("auth.login"))


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    # Displays error message on website
    msg = ""

    # When user clicks on the signup button,
    # check to make sure it's a POST request.
    if (
        request.method == "POST"
        and "firstname" in request.form
        and "lastname" in request.form
        and "username" in request.form
        and "password" in request.form
        and "email" in request.form
    ):
        firstname = request.form["firstname"]
        lastname = request.form["lastname"]
        username = request.form["username"]
        password = request.form["password"]
        email = request.form["email"]

        # Check if user exists in database
        db = app.config['DATABASE']
        cursor: MySQLdb.cursors.Cursor = db.connection.cursor(
            MySQLdb.cursors.DictCursor
        )
        cursor.execute("SELECT * FROM users_tb WHERE username = %s", (username,))
        user = cursor.fetchone()

        # Show error and validation checks if user exists
        if user:
            msg = "Username is already taken. Please choose a different one."
        elif not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            msg = "Invalid email address."
        elif not re.match(r"[A-Za-z0-9]+", username):
            msg = "Username must contain only characters and numbers."
        elif not username or not password or not email:
            msg = "Please fill out the form completely."
        else:
            # Hash the password
            hashed_password = password + app.secret_key
            hashed_password = hashlib.sha1(hashed_password.encode())
            password = hashed_password.hexdigest()
            
            # Creation date
            creation_date = datetime.now()

            # Create new account and store in database
            cursor.execute(
                "INSERT INTO users_tb (first_name, last_name, username, password, email, creation_date) VALUES(%s, %s, %s, %s, %s, %s)",
                (
                    firstname,
                    lastname,
                    username,
                    password,
                    email,
                    creation_date,
                ),
            )
            db.connection.commit()
            db.connection.close()

            # msg = "You have successfully signed up for Fakebook!"
            return redirect(url_for("auth.login"))

    # If the signup page has an empty box
    elif request.method == "POST":
        msg = "Please fill out the form completely"

    return render_template("signup.html", msg=msg)

src/Fakebook/views.py
from .models.user import User
from .models.post import Post
from .models.enums import FriendRequestErrors
from flask import current_app as app
from flask import Blueprint, render_template, redirect, request, url_for, session


views = Blueprint("views", __name__)


@views.route("/")
def home():
    if "loggedin" not in session:
        return redirect(url_for("auth.login"))

    # Displays error message on website
    msg = ""

    if request.method == "GET":
        db = app.config["DATABASE"]
        user = User(db, session["id"])

        user.timeline.view_timeline()
        posts = user.timeline.posts
        friend_requests = user.friend_requests

        if len(posts) != 0:
            return render_template(
                "home.html",
                posts=posts,
                friendrequests=friend_requests,
            )
        else:
            msg = "No Posts..."

    return render_template("home.html", msg=msg, friendrequests=friend_requests)


@views.route("/friends")
def friends():
    if "loggedin" in session:
        # Displays error message on website
        msg = ""

        if request.method == "GET":
            db = app.config["DATABASE"]
            user = User(db, session["id"])
            friends = user.friends_list.friends
            friend_requests = user.friend_requests

            if friends:
                return render_template(
                    "friends.html", friends=friends, friendrequests=friend_requests
                )
            else:
                return render_template(
                    "friends.html", friends=None, friend_requests=None
                )
    else:
        msg = "Failed to load friends page"

    return render_template("friends.html", msg=msg)


@views.route("/search_user", methods=["GET"])
def search_user():
    # Display error message on website
    msg = ""

    # Check if POST request has at least a post description
    if (
        "loggedin" in session
        and request.method == "GET"
        and "searchbar" in request.args
        and "searchbar-submit" in request.args
    ):
        username = request.args["searchbar"]
        db = app.config["DATABASE"]
        cursor = db.connection.cursor()

        # Get user
        cursor.execute(
            "SELECT id, first_name, last_name FROM users_tb WHERE username = %s",
            (username,),
        )
        user = cursor.fetchone()

        if user:
            fullname = f"{user[1]} {user[2]}"
            return render_template(
                "search.html",
                searchedid=user[0],
                searchedfullname=fullname,
                searcheduser=username,
            )
        else:
            msg = "Failed to find user " + username
    else:
        msg = "User search failed..."
    return render_template("search.html", msg=msg)


@views.route("/send_friend_request", methods=["POST"])
def send_friend_request():
    # Display error message on website
    msg = ""

    # Check if POST request has at least a post description
    if (
        "loggedin" in session
        and request.method == "POST"
        and "friend-id" in request.form
        and "friend-username" in request.form
    ):
        friend_id = request.form["friend-id"]
        friend_username = request.form["friend-username"]
        db = app.config["DATABASE"]

        user = User(db, session["id"])
        status = user.send_friend_request(friend_id)

        if status == FriendRequestErrors.INVALID_USER:
            msg = "Could not find user: " + friend_username
        elif status == FriendRequestErrors.FRIEND_REQUEST_ALREADY_EXISTS:
            msg = "Friend request for " + friend_username + " already exists."
        else:
            return redirect(url_for("views.home"))
    else:
        msg = "Unable to send friend request..."

    return render_template("search.html", msg=msg)


@views.route("/accept_friend_request", methods=["POST"])
def accept_friend_request():
    # Display error message on website3
    msg = ""

    # Check if it's a POST request when clicking the like button
    if (
        "loggedin" in session
        and request.method == "POST"
        and "friend-id" in request.form
        and "accept-friend-request" in request.form
    ):
        friend_id = int(request.form["friend-id"])

        db = app.config["DATABASE"]
        user = User(db, session["id"])
        user.friend_requests[friend_id].accept_friend_request()

        return redirect(url_for("views.home"))
    else:
        msg = "Failed to accept friend request"

    return render_template("home.html", msg=msg)


@views.route("/decline_friend_request", methods=["POST"])
def decline_friend_request():
    # Display error message on website3
    msg = ""

    # Check if it's a POST request when clicking the like button
    if (
        "loggedin" in session
        and request.method == "POST"
        and "friend-id" in request.form
        and "decline-friend-request" in request.form
    ):
        friend_id = int(request.form["friend-id"])

        db = app.config["DATABASE"]
        user = User(db, session["id"])
        user.friend_requests[friend_id].decline_friend_request()

        return redirect(url_for("views.home"))
    else:
        msg = "Failed to decline friend request"

    return render_template("home.html", msg=msg)


@views.route("/profile")
def profile():
    if "loggedin" in session and request.method == "GET" and "user-id" in request.args:
        user_id = int(request.args["user-id"])

        db = app.config["DATABASE"]
        user = User(db, user_id)
        fullname = f"{user.name.first_name} {user.name.last_name}"
        username = user.username

        friends = user.friends_list.friends
        if friends:
            if user_id in user.friends_list.friends:
                return render_template(
                    "profile.html", user=user, fullname=fullname, username=username
                )
        else:
            return render_template(
                "profile.html",
                user=user,
                userid=user_id,
                fullname=fullname,
                username=username,
            )
    else:
        db = app.config["DATABASE"]
        user = User(db, session["id"])

        return render_template(
            "profile.html",
            user=user,
            fullname=session["fullname"],
            username=session["username"],
        )


@views.route("/edit_bio", methods=["POST"])
def edit_bio():
    # Display error message on website
    msg = ""

    if (
        "loggedin" in session
        and request.method == "POST"
        and "user-id" in request.form
        and "bio-textbox" in request.form
    ):
        user_id = request.form["user-id"]
        bio_textbox = request.form["bio-textbox"]

        db = app.config["DATABASE"]
        user = User(db, user_id)
        user.edit_bio(bio_textbox)

        # Crashes when uncommented. Need to fix
        # post = Post(db=db, post_id=post_id)
        # return render_template("post.html", post=post)

        return redirect(url_for("views.profile"))

    elif "loggedin" in session and request.method == "POST":
        msg = "Text is required to edit bio."
    else:
        msg = "Unable to edit bio..."

    return render_template("profile.html", msg=msg)


@views.route("/create_post", methods=["POST"])
def create_post():
    # Display error message on website
    msg = ""

    # Check if POST request has at least a post description
    if (
        "loggedin" in session
        and request.method == "POST"
        and "create-post-textbox" in request.form
    ):
        post_description = request.form["create-post-textbox"]
        # Check if there's a post media (this is optional)
        # post_media = request.form["create-post-media"]

        db = app.config["DATABASE"]
        user = User(db, session["id"])
        user.make_post(post_description)

        return redirect(url_for("views.home"))

    elif "loggedin" in session and request.method == "POST":
        msg = "Post description is required to create a post."
    else:
        msg = "Unable to create post..."

    return render_template("home.html", msg=msg)


@views.route("/like_post", methods=["POST"])
def like_post():
    # Display error message on website3
    msg = ""

    # Check if it's a POST request when clicking the like button
    if (
        "loggedin" in session
        and request.method == "POST"
        and "post-id" in request.form
        and "like-post-submit" in request.form
    ):
        post_id = request.form["post-id"]

        db = app.config["DATABASE"]
        user = User(db, session["id"])
        user.like_post(post_id=post_id)

        return redirect(url_for("views.home"))
    else:
        msg = "Failed to like post"

    return render_template("home.html", msg=msg)


@views.route("/view_comments", methods=["GET"])
def view_comments():
    # Display error message on website3
    msg = ""

    # Check if it's a POST request when clicking the like button
    if (
        "loggedin" in session
        and request.method == "GET"
        and "post-id" in request.args
        and "comment-post-submit" in request.args
    ):
        post_id = request.args["post-id"]

        db = app.config["DATABASE"]
        post = Post(db, post_id=post_id)
        post.get_comments()

        if post:
            return render_template("post.html", post=post)
        else:
            msg = "Failed to view comments."
    else:
        msg = "Failed to view comments."

    return render_template("post.html", msg=msg)


@views.route("/comment", methods=["POST"])
def comment():
    # Display error message on website
    msg = ""

    if (
        "loggedin" in session
        and request.method == "POST"
        and "post-id" in request.form
        and "comment-textbox" in request.form
    ):
        post_id = request.form["post-id"]
        comment_text = request.form["comment-textbox"]

src/Fakebook/templates/Login.html
{% extends "base.html" %}

{% block title %}Fakebook - Login{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
{% endblock %}

{% block content %}
<div class="login-wrapper">
    <div class="login-form-container">
        <div class="login-greeter">
            <h1>Fakebook</h1>
            <label>Connect with friends around the world.</label>
        </div>

        <div class="login-container">
            <form action="{{ url_for('auth.login') }}" method="post">
                <div class="login-msg">{{ msg }}</div>
                <input type="text" name="username" id="username" placeholder="Username" maxlength="25" required>
                <input type="password" name="password" id="password" placeholder="Password" maxlength="25" required>
                <input class="login-button" type="submit" value="Login">
            </form>

            <a href="">Forgot Password?</a>

            <button onclick="window.location.href=`{{ url_for('auth.signup') }}`">Signup</button>
        </div>
    </div>
    <!-- <div class="login-image">
        <img src="{{ url_for('static', filename='images/bulldog.png') }}" alt="Bulldog">
    </div> -->
</div>
{% endblock %}

src/Fakebook/templates/home.html
{% extends "layout.html" %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% endblock %}

{% block content %}
<div class="middle">
    <!---->
    <form class="create-post" action="{{ url_for('views.create_post') }}" method="post" autocomplete="off">
        <input name="create-post-textbox" id="create-post-textbox" type="text" placeholder="What's on your mind?"
            maxlength="250" required>
        <!--<input type="file" name="create-post-media" id="create-post-media" accept="image/png, image/jpeg" /> -->
        <input type="submit" name="create-post-submit" id="create-post-submit" value="Post" class="btn btn-primary">
    </form>

    <!------------FEED---------------------->
    <div class="feeds">
        {% if msg %}
        <h3>{{ msg }}</h3>
        {% else %}
        {% for post_id, post in posts.items() %}
        <div class="feed">
            <div class="head">
                <!------Username and Date------->
                <div class="user">
                    <div class="info">
                        <h3>{{ post['creator_name'] }}</h3>
                        <small>{{ post['creation_date'] }}</small>
                    </div>
                </div>

                <!--Post Options-->
                <span class="edit">
                    <i class="uil uil-ellipsis-h"></i>
                </span>
            </div>

            <div class="body">
                <!-- <div class="post-image">
                    <img src="images/terrell.jpg" alt="Terrell Owens">  Image added here 
                </div> -->

                <div class="likes-counter">
                    <span><i class="uil uil-thumbs-up"></i></span>
                    <label>{{ post['likes'] }}</label>
                    <!--<span><i class="uil uil-comment"></i></span> -->
                    <!--<span><i class="uil uil-share"></i></span> -->
                </div>

                <div class="caption">
                    <p>{{ post['description'] }}</p>
                </div>

                <div class="action-buttons">
                    <div class="interaction-buttons">
                        <!--Like Post-->
                        <form action="{{ url_for('views.like_post') }}" method="post">
                            <input type="hidden" name="post-id" id="post-id" value="{{ post['post_id'] }}">
                            <input class="like-btn button" type="submit" name="like-post-submit" id="like-post-submit"
                                value="Like">
                        </form>
                    </div>

                    <!--<div class="bookmark">
                        <span><i class="uil uil-bookmark"></i></span>
                    </div> -->
                </div>
                <form action="{{ url_for('views.view_comments') }}" method="get">
                    <input type="hidden" name="post-id" id="post-id" value="{{ post['post_id'] }}">
                    <input class="button text-muted" type="submit" name="comment-post-submit" id="comment-post-submit"
                        value="View Comments">
                </form>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

src/Fakebook/templates/layout.html
{% extends "base.html" %}

{% block nav %}
<nav>
    <div class="container">
        <a href="{{ url_for('views.home') }}">
            <h2 class="logo">Fakebook</h2>
        </a>

        <div class="search-bar">
            <i class="uil uil-search"></i>
            <form action="{{ url_for('views.search_user') }}" method="get">
                <input type="search" name="searchbar" id="searchbar" placeholder="Search for users" maxlength="50"
                    required>
                <input type="submit" name="searchbar-submit" id="searchbar-submit" value="">
            </form>
        </div>

        <div class="user-profile">
            <img src="{{ url_for('static', filename='images/bulldog.png') }}" alt="Profile" id="profileImg"
                class="profile-img">

            <div id="profileOptions" class="profile-options">
                <a href="{{ url_for('views.profile') }}">View Profile</a>
                <!--<a href="path-to-notifications.html">Notifications</a> -->
                <!--<a href="path-to-account-details.html">Account Details</a> -->
                <!--<a href="path-to-bookmarks.html">Bookmarks</a> -->
                <!--<a href="{{ url_for('views.friends') }}">Friends</a> -->
                <!--<a href="path-to-display-settings.html">Display</a> -->
                <a href="{{ url_for('auth.logout') }}">Logout</a>
            </div>
        </div>
    </div>
</nav>
{% endblock %}

{% block left_sidebar %}
<div class="left">
    <a class="profile">
        <!---<div class="profile-photo">-->
        <div class="handle">
            <h4>{{ session["fullname"] }}</h4>
            <p class="text-muted">
                @{{ session["username"] }}
            </p>
        </div>
    </a>

    <div class="sidebar">
        <a class="menu-item" href="{{ url_for('views.home') }}">
            <span><i class="uil uil-home"></i></span>
            <h3>Home</h3>
        </a>

        <a class="menu-item" href="{{ url_for('views.friends') }}">
            <span><i class="uil uil-users-alt"></i></span>
            <h3>Friends</h3>
        </a>

        <a class="menu-item" href="{{ url_for('views.profile') }}">
            <span><i class="uil uil-user-circle"></i></span>
            <h3>Profile</h3>
        </a>
        <!--
        <a class="menu-item">
            <span><i class="uil uil-bell"></i></span><h3>Notifications</h3>
        </a>
        <a class="menu-item">
            <span><i class="uil uil-envelopes"></i></span><h3>Messages</h3>
        </a>
        <a class="menu-item">
            <span><i class="uil uil-bookmark"></i></span><h3>Saved</h3>
        </a>
        <a class="menu-item">
            <span><i class="uil uil-palette"></i></span><h3>Theme</h3>
        </a>
        Other shit that may or may not be added later.-->

        <!--<a class="menu-item">
            <span><i class="uil uil-setting"></i></span>
            <h3>Settings</h3>
        </a> -->

    </div>
    <!-- <label for="create-post" class="btn btn-primary">Create Post</label> -->
</div>
{% endblock %}

{% block content %}{% endblock %}

{% block right_sidebar %}
<div class="right">
    <!----->
    <!-- <div class="messages"> -->
    <!-- <div class="heading"> -->
    <!-- <h4>Messages</h4><i class="uil uil-envelopes"></i> -->
    <!-- </div> -->

    <!----Search again -->
    <!-- <div class="search-bar"> -->
    <!-- <i class="uil uil-search"></i> -->
    <!-- <input type="search" placeholder = "Filter through messages" id="message-search"> -->
    <!-- </div> -->
    <!-- </div> -->
    <!-- Requests section -->
    <div class="friend-requests">
        <h4>Friend Requests</h4>

        {% if friendrequests %}
        {% for request_id, request in friendrequests.items() %}
        <div class="request">
            <div class="info">
                <div>
                    <h5>{{ request['friend_accepter_username'] }}</h5>
                </div>
            </div>

            <div class="action">
                <!--Accept Friend Request-->
                <form action="{{ url_for('views.accept_friend_request') }}" method="post">
                    <input type="hidden" name="friend-id" id="friend-id" value="{{ request_id }}">
                    <input class="btn btn-primary" type="submit" name="accept-friend-request" id="accept-friend-request"
                        value="Accept">
                </form>

                <!--Decline Friend Request-->
                <form action="{{ url_for('views.decline_friend_request') }}" method="post">
                    <input type="hidden" name="friend-id" id="friend-id" value="{{ request_id }}">
                    <input class="btn" type="submit" name="decline-friend-request" id="decline-friend-request"
                        value="Decline">
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h3>No Friend Requests...</h3>
        {% endif %}
    </div>
</div>
{% endblock %}

src/Fakebook/templates/post.html
{% extends 'layout.html' %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/post.css') }}">
{% endblock %}

{% block title %}Fakebook - Post{% endblock %}

{% block content %}
{% if msg %}
<h3>{{ msg }}</h3>
{% else %}
<div class="post-page">
    <div class="feed"
        style="margin-left: 15rem; margin-top: 3rem; background-color: white; display: flex; flex-direction: column; align-items: start; justify-content: space-evenly; border-radius: 2rem; padding: 1rem;">
        <div class="head" style="display: flex; flex-direction: row;">
            <!------Username and Date------->
            <div class="user">
                <div class="info">
                    <h3>{{ post['creator_name'] }}</h3>
                    <small>{{ post['creation_date'] }}</small>
                </div>
            </div>

            <!--Post Options-->
            <span class="edit" style="margin-left: 25rem;">
                <i class="uil uil-ellipsis-h"></i>
            </span>
        </div>

        <div class="body">
            <!-- <div class="post-image">
            <img src="images/terrell.jpg" alt="Terrell Owens">  Image added here 
        </div> -->

            <div class="likes-counter">
                <span><i class="uil uil-thumbs-up"></i></span>
                <label>{{ post['likes'] }}</label>
                <!--<span><i class="uil uil-comment"></i></span> -->
                <!--<span><i class="uil uil-share"></i></span> -->
            </div>

            <div class="caption">
                <p>{{ post['description'] }}</p>
            </div>

            <div class="action-buttons">
                <div class="interaction-buttons">
                    <!--Like Post-->
                    <form action="{{ url_for('views.like_post') }}" method="post">
                        <input type="hidden" name="post-id" id="post-id" value="{{ post['post_id'] }}">
                        <input class="like-btn" type="submit" name="like-post-submit" id="like-post-submit"
                            value="Like">
                    </form>
                </div>

                <!--<div class="bookmark">
                <span><i class="uil uil-bookmark"></i></span>
            </div> -->
            </div>

            <div class="comment-box-wrapper">
                <form action="{{ url_for('views.comment') }}" method="post" autocomplete="on">
                    <textarea rows="5" name="comment-textbox" id="comment-textbox"
                        placeholder="What's on your mind {{ username }}?" maxlength="500" required></textarea>
                    <input type="hidden" name="post-id" id="post-id" value="{{ post['post_id'] }}">
                    <input type="submit" name="comment-submit" id="comment-submit" value="Comment" />
                </form>
            </div>
        </div>
    </div>

    <div class="comment-area">
        <h4>Comments</h4>
        {% if post['comments'] %}
        {% for comment_id, comment in post['comments'].items() %}
        {% if comment['comment_replied_to'] == None %}
        <div class="comment">
            <div class="comment-details">
                <h4>{{ comment['commenter_name'] }}</h4>
                <label>{{ comment['creation_date'] }}</label>
            </div>
            <p>{{ comment['text'] }}</p>

            <hr class="solid">

            <form action="{{ url_for('views.reply') }}" method="post">
                <input type="hidden" name="post-id" id="post-id" value="{{ post['post_id'] }}">
                <input type="hidden" name="comment-id" id="post-id" value="{{ comment_id }}">
                <textarea rows="2" name="reply-textbox" id="reply-textbox" placeholder="Reply Here" maxlength="250"
                    required></textarea>
                <input type="submit" name="reply-submit" id="reply-submit" value="Reply" />
            </form>
        </div>
        {% endif %}
        {% endfor %}
        {% else %}
        <h4>No Comments...</h4>
        {% endif %}
    </div>
</div>
{% endif %}

{% endblock %}

src/Fakebook/templates/signup.html
{% extends "base.html" %}

{% block title %}Fakebook - Signup{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/signup.css') }}">
{% endblock %}

{% block content %}
<div class="signup">
    <h2>Signup for Fakebook</h2>

    <form action="{{ url_for('auth.signup') }}" method="post" autocomplete="off">
        <input type="text" name="firstname" id="firstname" placeholder="First Name" maxlength="25" required>
        <input type="text" name="lastname" id="lastname" placeholder="Last Name" maxlength="25" required>
        <input type="text" name="username" id="username" placeholder="Username" maxlength="25" required>
        <input type="email" name="email" id="email" placeholder="Email" maxlength="100" required>
        <input type="password" name="password" id="password" placeholder="Password" maxlength="25" required>
        <input type="submit" value="Signup">
        <div class="login-msg">{{ msg }}</div>
    </form>
</div>
{% endblock %}